name: Copywrite

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  copywrite:
    name: Run Header Copyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install Copywrite
        id: install
        uses: hashicorp/setup-copywrite@v1.0.0

      - name: Output Installed Copywrite Version
        run: echo "Installed Copywrite CLI ${{steps.install.outputs.version}}"

      - name: Run Copywrite Header Compliance
        run: copywrite headers --plan
